# Generated by Django 4.1.4 on 2022-12-22 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(default='images/nav/default_user.jpg', upload_to='users/%Y/%m/%d', verbose_name='Фото')),
                ('photo_background', models.ImageField(default='images/nav/default_background.png', upload_to='users/%Y/%m/%d', verbose_name='Задний фон')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('school', models.CharField(blank=True, max_length=150, null=True, verbose_name='Школа')),
                ('vk_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на вк')),
                ('inst_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на инсту')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
